name: bamboo
description: Bamboo makes it easy and fast to build adaptive apps for mobile, web and beyond with Flutter
version: 0.0.1
homepage: https://flutter.dev/custom-fonts/

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

